FROM gliderlabs/alpine:3.4
VOLUME /mnt/routes
EXPOSE 80

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/amaysim-au/logspout
WORKDIR /go/src/github.com/amaysim-au/logspout
RUN go get
CMD go get \
	&& go build -ldflags "-X main.Version dev" -o /bin/logspout \
	&& exec /bin/logspout
